/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/shared/AppBar.vue')['default']
    ConnectionConfirmationDialog: typeof import('./src/components/dialogs/ConnectionConfirmationDialog.vue')['default']
    ConnectPlatformDialog: typeof import('./src/components/dialogs/ConnectPlatformDialog.vue')['default']
    DesktopLayout: typeof import('./src/components/shared/DesktopLayout.vue')['default']
    DialogCloseBtn: typeof import('./src/components/core/DialogCloseBtn.vue')['default']
    LanguageSwitch: typeof import('./src/components/shared/LanguageSwitch.vue')['default']
    MetaButton: typeof import('./src/components/platforms/meta/MetaButton.vue')['default']
    MobileLayout: typeof import('./src/components/shared/MobileLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VerticalNavMenu: typeof import('./src/components/shared/VerticalNavMenu.vue')['default']
  }
}
