/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/account-setup/': RouteRecordInfo<'/account-setup/', '/account-setup', Record<never, never>, Record<never, never>>,
    '/ad-groups/[campaignId]/add/': RouteRecordInfo<'/ad-groups/[campaignId]/add/', '/ad-groups/:campaignId/add', { campaignId: ParamValue<true> }, { campaignId: ParamValue<false> }>,
    '/ad-groups/[campaignId]/edit/': RouteRecordInfo<'/ad-groups/[campaignId]/edit/', '/ad-groups/:campaignId/edit', { campaignId: ParamValue<true> }, { campaignId: ParamValue<false> }>,
    '/ads/[adGroupId]/add/': RouteRecordInfo<'/ads/[adGroupId]/add/', '/ads/:adGroupId/add', { adGroupId: ParamValue<true> }, { adGroupId: ParamValue<false> }>,
    '/ads/add': RouteRecordInfo<'/ads/add', '/ads/add', Record<never, never>, Record<never, never>>,
    '/assistant/': RouteRecordInfo<'/assistant/', '/assistant', Record<never, never>, Record<never, never>>,
    '/assistant/designer/': RouteRecordInfo<'/assistant/designer/', '/assistant/designer', Record<never, never>, Record<never, never>>,
    '/assistant/writer/': RouteRecordInfo<'/assistant/writer/', '/assistant/writer', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/campaigns/': RouteRecordInfo<'/campaigns/', '/campaigns', Record<never, never>, Record<never, never>>,
    '/campaigns/add': RouteRecordInfo<'/campaigns/add', '/campaigns/add', Record<never, never>, Record<never, never>>,
    '/campaigns/edit/[id]': RouteRecordInfo<'/campaigns/edit/[id]', '/campaigns/edit/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/link-ad-accounts': RouteRecordInfo<'/link-ad-accounts', '/link-ad-accounts', Record<never, never>, Record<never, never>>,
    '/link-ad-accounts/': RouteRecordInfo<'/link-ad-accounts/', '/link-ad-accounts', Record<never, never>, Record<never, never>>,
    '/link-ad-accounts/add-store': RouteRecordInfo<'/link-ad-accounts/add-store', '/link-ad-accounts/add-store', Record<never, never>, Record<never, never>>,
    '/link-ad-accounts/connect-platform': RouteRecordInfo<'/link-ad-accounts/connect-platform', '/link-ad-accounts/connect-platform', Record<never, never>, Record<never, never>>,
    '/marketing-consultations/': RouteRecordInfo<'/marketing-consultations/', '/marketing-consultations', Record<never, never>, Record<never, never>>,
    '/marketing-consultations-orders/': RouteRecordInfo<'/marketing-consultations-orders/', '/marketing-consultations-orders', Record<never, never>, Record<never, never>>,
    '/reports/': RouteRecordInfo<'/reports/', '/reports', Record<never, never>, Record<never, never>>,
    '/reports/OrderedPlatformsByPerformance': RouteRecordInfo<'/reports/OrderedPlatformsByPerformance', '/reports/OrderedPlatformsByPerformance', Record<never, never>, Record<never, never>>,
    '/reports/TopAndLeastCampaigns': RouteRecordInfo<'/reports/TopAndLeastCampaigns', '/reports/TopAndLeastCampaigns', Record<never, never>, Record<never, never>>,
    '/rules': RouteRecordInfo<'/rules', '/rules', Record<never, never>, Record<never, never>>,
    '/rules/': RouteRecordInfo<'/rules/', '/rules', Record<never, never>, Record<never, never>>,
    '/rules/campaigns/': RouteRecordInfo<'/rules/campaigns/', '/rules/campaigns', Record<never, never>, Record<never, never>>,
    '/rules/communication/': RouteRecordInfo<'/rules/communication/', '/rules/communication', Record<never, never>, Record<never, never>>,
  }
}
