const matrixTheme = {
  dark: false,
  colors: {
    background: '#F8F7FA',
    surface: '#FFFFFF',
    'surface-bright': '#F8F7FA',
    'surface-light': '#EEEEEE',
    'surface-variant': '#706D79',
    'on-surface-variant': '#EEEEEE',
    primary: '#4E1AC7',
    'primary-darken-1': '#1F5592',
    secondary: '#F8F7FA',
    'secondary-darken-1': '#018786',
    error: '#F54A41',
    info: '#A580BA',
    success: '#24C87E',
    'on-success': '#ffffff',
    warning: '#FB813E',
    black: "#000"
  },
  variables: {
    'border-color': '#000000',
    'border-opacity': 0.12,
    'high-emphasis-opacity': 0.87,
    'medium-emphasis-opacity': 1,
    'disabled-opacity': 0.38,
    'idle-opacity': 0.04,
    'hover-opacity': 0.04,
    'focus-opacity': 0.12,
    'selected-opacity': 0.08,
    'activated-opacity': 0.12,
    'pressed-opacity': 0.12,
    'dragged-opacity': 0.08,
    'theme-kbd': '#212529',
    'theme-on-kbd': '#FFFFFF',
    'theme-code': '#F5F5F5',
    'theme-on-code': '#000000',
    'theme-on-background': '#706D79',
    'btn-size': '1rem',
    'dark-1': '#1F1625',
    'dark-2': '#41324C',
  },
}

export default matrixTheme
